// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcH_Ek7AcNp9bFkiYWG49lF27jlXGFrZY',
    appId: '1:960879271216:web:a2815a5367816271dabcf5',
    messagingSenderId: '960879271216',
    projectId: 'ecommerce-project-2e1b6',
    authDomain: 'ecommerce-project-2e1b6.firebaseapp.com',
    storageBucket: 'ecommerce-project-2e1b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD13I4bCPRm915tkUjWk6qtShj9HCaD0g',
    appId: '1:960879271216:android:44608fff04d86cfddabcf5',
    messagingSenderId: '960879271216',
    projectId: 'ecommerce-project-2e1b6',
    storageBucket: 'ecommerce-project-2e1b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5pn-ypbycw5czUqNw5-UjEA-eG-tuP_Y',
    appId: '1:960879271216:ios:e46debeebffab5dcdabcf5',
    messagingSenderId: '960879271216',
    projectId: 'ecommerce-project-2e1b6',
    storageBucket: 'ecommerce-project-2e1b6.firebasestorage.app',
    iosBundleId: 'com.example.projetTd2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5pn-ypbycw5czUqNw5-UjEA-eG-tuP_Y',
    appId: '1:960879271216:ios:e46debeebffab5dcdabcf5',
    messagingSenderId: '960879271216',
    projectId: 'ecommerce-project-2e1b6',
    storageBucket: 'ecommerce-project-2e1b6.firebasestorage.app',
    iosBundleId: 'com.example.projetTd2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcH_Ek7AcNp9bFkiYWG49lF27jlXGFrZY',
    appId: '1:960879271216:web:047882871f9a229fdabcf5',
    messagingSenderId: '960879271216',
    projectId: 'ecommerce-project-2e1b6',
    authDomain: 'ecommerce-project-2e1b6.firebaseapp.com',
    storageBucket: 'ecommerce-project-2e1b6.firebasestorage.app',
  );
}
